server:
  port: 18090
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  task:
    execution:
      thread-name-prefix: cart-async-
      pool:
        core-size: 100
        max-size: 200
        queue-capacity: 5000
        keep-alive: 60s
        allow-core-thread-timeout: true
      shutdown:
        await-termination: true
        await-termination-period: 100

    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  thymeleaf:
    cache: false
  elasticsearch:
    rest:
      uris: http://192.168.153.166:9200
  jackson:
    default-property-inclusion: non_null
  rabbitmq:
    host: 192.168.153.166
    virtual-host: /fengge
    username: fengge
    password: fengge
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 1
        concurrency: 8
  redis:
    host: 192.168.153.166
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/guli_cart
    username: root
    password: 669190


feign:
  sentinel:
    enabled: true
jwt:
  pubKeyPath: D:\JavaCode\rsa\rsa.pub
  cookieName: GMALL-TOKEN
  userKeyName: user-key
  expire: 15552000

