server:
  port: 18089
spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848


    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411
    discovery-client-enabled: false
    sender:
      type: web
  sleuth:
    sampler:
      probability: 1
  thymeleaf:
    cache: false
  elasticsearch:
    rest:
      uris: http://192.168.153.166:9200
  jackson:
    default-property-inclusion: non_null
  rabbitmq:
    host: 192.168.153.166
    virtual-host: /fengge
    username: fengge
    password: fengge
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 1
        concurrency: 8
feign:
  sentinel:
    enabled: true
jwt:
  pubKeyPath: D:\JavaCode\rsa\rsa.pub
  priKeyPath: D:\JavaCode\rsa\rsa.pri
  secret: 1645351@dwjio214as
  expire: 240
  cookieName: GMALL-TOKEN
  unick: unick
